# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=40, verbose_name='Apellido paterno')),
                ('ap_materno', models.CharField(max_length=40, verbose_name='Apellido materno')),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
